### ISSUE TITLE
Error in extracting more than one file in 01_workOffline.sh

### ISSUE THREAD

**Issue by deshawes** [gitmachtl/scripts#15]
When extracting more than one attached file from offlineTransfer.json, the second and subsequent files are not extracted. 
The script 01_workOffline.sh changes the offlineJson variable within the for loop.

Possible correction 
at line 709 Insert: 
 offlineJSONExtract=${offlineJSON}

at lines 729-731 replace with:
 offlineJSONExtract=$( jq ".history += [ { date: \"$(date -R)\", action: \"extracted file '${filePath}'\" } ]" <<< ${offlineJSONExtract})
 offlineJSONExtract=$( jq "del (.files.\"${filePath}\")" <<< ${offlineJSONExtract})
 echo "${offlineJSONExtract}" > ${offlineFile}

at line 740 replace with:
filesCnt=$(jq -r ".files | length" <<< ${offlineJSONExtract});

**Comment by gitmachtl** [comment]
hi, after extracting a attached file, the scripts outputs the new list after the command was execute. so you have to look for the new file id to extract the next one. otherwise the file would grow and already extracted files would sit on a id-place.

**Comment by gitmachtl** [comment]
ok right, there is something wrong if more than one files is attached... i will look into it

**Comment by gitmachtl** [comment]
Bug was corrected in the updated release, thx!
