### ISSUE TITLE
01_workOffline.sh:  Incorrect history entry when attaching a file to offlineTransfer.json

### ISSUE THREAD

**Issue by deshawes** [gitmachtl/scripts#16]
Cosmetic change to 01_workOffline.sh
Last action for an attach is displayed as "signed pool registration transaction for '', payment via ''" 
at line 153 replace with:
offlineJSON=$( jq ".history += [ { date: \"$(date -R)\", action: \"attached file '${fileToAttach}'\" } ]" <<< ${offlineJSON})

**Comment by gitmachtl** [comment]
:smiley: yeah, thx. have not seen this. typical copy&paste error. i have corrected it for the next version
