### ISSUE TITLE
01_workOffline.sh, 05c_regStakepoolCert.sh: Metadata hash check incorrect for metadata json files without final LF

### ISSUE THREAD

**Issue by deshawes** [gitmachtl/scripts#17]
If the last line in the metadata JSON file uploaded to the pool metadata server is not terminated with a LF there is an issue in the scripts  01_workOffline.sh and 05c_regStakepoolCert.sh. 
In this edge case the hash calculation check succeeds when executing a re-registration of the stake pool certificate even though the uploaded file and the local metadata json file differ by the LF. The scripts inadvertently add a LF to the returned metadata json file from the pool meta URL causing an incorrect hash to be calculated.
(This is not an issue if the metadata json files were originally created by 05a_genStakepoolCert.sh and the json file was uploaded correctly. The problem is that the script does not pick up that the uploaded file is incorrect.)
Possible fix in 01_workOffline.sh (1.24.2)
replace line 595:  tmpCheckJSON=$(echo -n "${tmpMetadataJSON}" | jq . 2> /dev/null)
replace line 598:  onlineMetaHash=$(${cardanocli} ${subCommand} stake-pool metadata-hash --pool-metadata-file <(echo -n "${tmpMetadataJSON}") )
replace line 605: echo -n "${tmpMetadataJSON}"

Similarly for 05c_regStakepoolCert.sh

**Comment by gitmachtl** [comment]
hmm... thats really a rare case, because there is a given workflow and that is that the metadata file is generated by the 05a script. and the hash from that metadata file is stored in the pool.json file for this later comparision. so, if the generated metadata file is not uploaded in binary mode correctly to the webserver, the downloaded file would not generate the same hash hex. can you give me an example on how such a rare mismatch could happend? uploading metadata info to github and co via copy/past of text is never a good idea. and you can't bring an external hash metahex in the pool.json because it is generated every time again when running 05a to get a new certificate for the pool registration.

**Comment by gitmachtl** [comment]
it would really come down to only this line:
`onlineMetaHash=$(${cardanocli} ${subCommand} stake-pool metadata-hash --pool-metadata-file <(echo "${tmpMetadataJSON}") )`

but echo "xxx" and echo -n "xxx" does not give you the same result, so also not the same hash

**Comment by deshawes** [comment]
I have had the metadata info on github since day one of the mainnet, I chose a  format for the json file without a terminating LF on the last line.  As it turned out most SPO's and your scripts generated a metadata with a terminating LF.  I recently updated pledge on my pool using your offline scripts without changing the metadata file and so did not upload the generated file. When I executed the online transaction the metadata hash check passed.  I became suspicious when my pool dropped out of daedulus. The script had generate the same hash for the original uploaded metadata json even though it did not match the newly generated metadata.
The echo, without the -n flag,  appends a LF to the result of the curl of the metadata.json if the last character is not a LF.  Resulting in the same hash for what are dissimilar files. Similarly the echo input to the cardano-cli metadata-hash calculation may append a LF.   
It is possible for some one to do a cut and paste dropping the last LF and your script missing the error.  I know I should follow your directions to the letter and I would not have any issue but with the current state of daedulus and the SMASH server I would rather avoid changing something that is working.
I accept this is a weird edge case.

**Comment by deshawes** [comment]
echo -n is not removing a LF, it is just not adding a LF to the echoed string

**Comment by gitmachtl** [comment]
Can you give me the url of your metafile and also the registered hashhex?

**Comment by deshawes** [comment]
https://cardanoscan.io/pool/8ba11724b0b39f34223d166a752da604269db13562095d6386a14bb3?tab=metadata

https://bit.ly/8BALL_01

1) remote metadata.json without terminal LF is registered on chain with hash  
   
   240fde719f1443bfc61aaf3ad6f2e285b601b53683dd50863437f8fe4d9cc4d1

2) offline script created a metadata.json exactly the same as the remote file but with a terminal LF. 
   The script calculated its hash and stored it in the pool.json file as
  
   2be375e71f215bf7e5e2677051dd390082c1c13064b619901e868f5575edbf6d

3) online script calculated a hash for the remote metadata.json file it retrieved as 
  
   2be375e71f215bf7e5e2677051dd390082c1c13064b619901e868f5575edbf6d

   Metadata HASH Check, fetching the MetaData JSON file from https://bit.ly/8BALL_01: OK

   Does this look good for you, continue ? [y/N] N

4) The script had appended a LF to the retrieved file, calculated an incorrect hash and 
    would have registered the pool with a metadata hash that did not match the remote metadata file hash.

**Comment by gitmachtl** [comment]
Thx, so i played around with it and there was no "one fits all" solution when storing the requested metadata file in a variable. Both `echo` and `printf` cannot output the content of a file "as it is". They are both doing a CR/LF cut or appending in the opposite way. Hard  to catch such a rare case when you "step out of the workflow". 

It is now fixed for both scripts, the only solution was to really make this via a temporary file and work directly with the file. :smiley:

Can you please retry it on your side so we can close this Issue, thx!

**Comment by gitmachtl** [comment]
Have you retested this? Otherwise i will mark this issue as close. Thx.

**Comment by deshawes** [comment]
Haven’t tested your amended script yet, I will update my pool registration certificate again this epoch on mainnet and let you know. 

Regards,
Des Hawes

**Comment by deshawes** [comment]
Hi Martin 
the changes work perfectly, thank you. We can close this issue.

One small point, it would be helpful as an aid to manual checks if the metadata hash was displayed along with the success msg 
   "Metadata HASH Check, fetching the MetaData JSON file from https://bit.ly/8BALL_01: OK"  

thx
