### ISSUE TITLE
Address Handling in sendLovelaces.sh

### ISSUE THREAD

**Issue by samcgill29** [gitmachtl/scripts#2]
I tried to use this script to transfer ff-testnet lovelaces from one enterprise style address to another in separate directories.  I used the following syntax to launch the script:

./01_sendLovelaces.sh ../priv/payment1 pool-002_enterprise 4425831

payment1 is the send-from address
pool-002_enterprise is the receiver address
4425831 is the number of lovelace to send

Here is the output the script generated:
--------------------------------------------------------------------------------------------------------
Sending lovelaces from Address ../priv/payment1.addr to Address pool-002_enterprise.addr:

Current Slot-Height: 817630 (setting TTL to 827630)

Source Address ../priv/payment1.addr: 619ea1cba1088c5d9(truncated)
Destination Address pool-002_enterprise.addr: 617d6c090574b284858(truncated

2 UTXOs found on the source Addr!

HASH: 1f620efdfa52e8(truncated)   INDEX: 0        LOVELACES: 10000000
HASH: 69ebd62083d6(truncarted)   INDEX: 1        LOVELACES: 4425831
Total lovelaces in UTX0:  14425831 lovelaces

Minimum Transaction Fee for 2x TxIn & 2x TxOut:  169725 lovelaces
Lovelaces to send to pool-002_enterprise.addr:  4425831 lovelaces
Lovelaces to return to ../priv/payment1.addr:  9830275 lovelaces

Building the unsigned transaction body:  tx_../priv/payment1.txbody

Error while writing unsigned shelley tx: tx_../priv/payment1.txbody: tx_../priv/payment1.txbody: openBinaryFile: does not exist (No such file or directory)
cat: tx_../priv/payment1.txbody: No such file or directory

Sign the unsigned transaction body with the ../priv/payment1.skey:  tx_../priv/payment1.tx

Error while reading unsigned shelley tx: tx_../priv/payment1.txbody: tx_../priv/payment1.txbody: openBinaryFile: does not exist (No such file or directory)
cat: tx_../priv/payment1.tx: No such file or directory

Does this look good for you, continue ? [y/N] N
-------------------------------------------------------------------------------------------------

Note the errors produced by the script. Perhaps it is not parsing the address name from the path correctly?  The receiver address was in the same directory so I don't know if both send and receive addresses would experience the same issue if a path was prepended to them when launching the script.

**Comment by gitmachtl** [comment]
you're right. error happend because it generates files with prefix tx_<givenname> and that was confusing the script. good point! the transaction files tx and txbody were the only two files using a prefix for the name itself. i corrected it, should now work. please give me a short feedback, thx.

**Comment by gitmachtl** [comment]
can it be closed?

**Comment by samcgill29** [comment]
I didn't try because the F&F network was down.  I will try again soon and respond here.

**Comment by samcgill29** [comment]
works.  Thanks!
