### ISSUE TITLE
not finding file - new issue

### ISSUE THREAD

**Issue by stackBlock** [gitmachtl/scripts#20]
I ran into a snag when running the scripts for the hardware wallet. As you can see below, the error is telling me to run the 05b script but I already did - that is the first command below... As you can see, 05b did not create owner.deleg.cert, it looks like it created ledgerowner.deleg.cert instead... What do you think? 

ledgerowner.deleg.cert       ledgerowner.staking.vkey  owner.staking.vkey   savvy.pool.id-bech
ledgerowner.payment.addr     owner.payment.addr        savvy.metadata.json  savvy.pool.json
ledgerowner.payment.hwsfile  owner.payment.skey        savvy.node.counter   savvy.vrf.skey
ledgerowner.payment.vkey     owner.payment.vkey        savvy.node.skey      savvy.vrf.vkey
ledgerowner.staking.addr     owner.staking.addr        savvy.node.vkey      smallwallet1.addr
ledgerowner.staking.cert     owner.staking.cert        savvy.pool.cert      smallwallet1.skey
ledgerowner.staking.hwsfile  owner.staking.skey        savvy.pool.id        smallwallet1.vkey
anthony@anthony-XPS-2720:~/cardanoSavvy/savvy$  **05b_genDelegationCert.sh savvy ledgerowner**

Version-Info: cli 1.25.1 / node 1.25.1 Scripts-Mode: online

Create a delegation registration certificate for Delegator ledgerowner.staking.vkey to the PoolNode savvy.node.vkey:

Delegation registration certificate: ledgerowner.deleg.cert
{
    "type": "CertificateShelley",
    "description": "Stake Address Delegation Certificate",
    "cborHex": "83028200581c0ab6b98c1bcd001f2a8ea298c899d217272f04e769c76d5562430ed1581ca7ce13b0e41364cfc59bfe81d499ee412b6d2cb13cbef01155743e87"
}

Created a delegation certificate which delegates funds from all stake addresses
associated with key ledgerowner.staking.vkey to the pool associated with savvy.node.vkey

anthony@anthony-XPS-2720:~/cardanoSavvy/savvy$ 05c_regStakepoolCert.sh savvy smallwallet1 REREG

Version-Info: cli 1.25.1 / node 1.25.1 Scripts-Mode: online

ERROR - "owner.deleg.cert" does not exist! **Please create it first with script 05b.**

**Comment by gitmachtl** [comment]
yes, but you also need your owner.deleg.cert or do you wanna swap directly from old owner to ledgerowner? in that case you will loose out rewards for 1 epoch. normally you just add the ledgerowner (what you did) and do a smooth transition. the importHelper did not create the delegation certificate for the old owner automatically. so just run 05b again for the oldowner "owner" :smiley:

**Comment by gitmachtl** [comment]
i now also added the autocreating of the delegation cert (like owner.deleg.cert) for each owner along with the key copy and address copy.

**Comment by stackBlock** [comment]
perfect, thanks I will try that. that makes sense...

**Comment by stackBlock** [comment]
Is there any way do keep the script from changing or requiring me to change my ticker: 

'Your poolMetaTicker was corrected from 'SAvvY' to 'SAVVY' to fit the rules! Are you ok with this ?'

This is messing up my hash - I tried to change it back after the script changed it but that did not work - the hash shown by 05c was the same after I manually changed it back to 'SAvvY'... 
Is there a work around so I do not have to change my metadata? I want the ticker to be 'SAvvY'. 
Thanks

**Comment by gitmachtl** [comment]
A new metadata hash will be created anyway, because it will not match up with existing CR/LF for example.

**Comment by gitmachtl** [comment]
You can comment out line 185 in the script 05a: (poolMetaTicker=${poolMetaTicker^^} #convert to uppercase)

**Comment by stackBlock** [comment]
everything looks good. Now I am waiting two epochs...

I have a few questions. 
1) is it true that I added an additional owner to my account?
2) is it true that I can pledge using either account?
3) does one owner have access to the other owners pledge? (I assume the answer is no)
4) if I keep both owners on my account, is there anyway the hardwallet pledge amount can be stolen if a bad actor gets access to my pool or the other owner information? (I am asking because I am considering keeping the second owner on the account as a backup and want to know if there is ANY risk to doing that).

Thanks for all your help. When this is fully transferred over, I will help you advertise this to the coincashew bunch if you would like... I really appreciate it!  
I have a youtube channel that is small but I just started doing daily updates for the catalyst project last week. If you have a proposal or are thinking about doing one and I can help in any way, please let me know.. (Channel is still very small right now but should gain traction in a few months if I do videos every weekday and get better at it. lol)

**Comment by gitmachtl** [comment]
1.) if you have added another owner entry into the pool.json file than yes the pool has now two owners.
2.) you can pledge from either yes, the sum of all your owner accounts must meet your registered pledge
3.) no, the two owners are completly separate, each has its own payment keys
4.) no, funds from a hardware wallet can only be "stolen" if you actually have the physical device and also the pin code. there is no way another owner account can get access to the funds of another owner.

i have checked the SAvvY pool here:
https://cardanoscan.io/pool/a7ce13b0e41364cfc59bfe81d499ee412b6d2cb13cbef01155743e87?tab=poolupdatehistory

it looks like your second owner is still delegated to another pool. have you run the 06_ command after the pool reregistration? don't miss this step. its not needed when using only cli keys, but with the hardware wallets this additional step is needed. 

thx yes, feel free to tell it to the coincashew guys. and thank you for bringing up some bugs. your case is cool because you had extended keys, thats not often the case, so i'am glad it works now like it should. :smiley:

**Comment by stackBlock** [comment]
I did run that last command..hmm. let me just double check

**Comment by stackBlock** [comment]
It's long but here is the output. I ran it again, but I do remember running
it the first time... let me know if it still doesn;t show up please:



anthony@anthony-XPS-2720:~/cardanoSavvy/savvy$ 06_regDelegationCert.sh
ledgerowner ledgerowner.payment

Version-Info: cli 1.25.1 / node 1.25.1 Scripts-Mode: online

Register Delegation Certificate ledgerowner.deleg.cert with funds from
Address ledgerowner.payment.addr:

Current Slot-Height: 21693349 (setting TTL[invalid_hereafter] to 21793349)

Pay fees from Address ledgerowner.payment.addr:
addr1q8934rcpfemk3jjf58nv023memne4cdd8h9zuj2er5f70wc2k6uccx7dqq0j4r4znryfn5shyuhsfemfcak42cjrpmgs2wdy04

1 UTXOs found on the Source Address!

Hash#Index:
4b9e7c37958a18ffbdb39ce0d9ce70778cd7e89137ce39197736f191238a704f#0 Amount:
2641234
-----------------------------------------------------------------------------------------------------
Total ADA on the Address:  2.641234 ADA / 2641234 lovelaces


Minimum transfer Fee for 1x TxIn & 1x TxOut & 1x Certificate:  0.180021 ADA
/ 180021 lovelaces

Minimum funds required for registration (Sum of fees):  0.180021 ADA /
180021 lovelaces

Lovelaces that will be return to payment Address (UTXO-Sum minus fees):
 2.461213 ADA / 2461213 lovelaces  (min. required 1000000 lovelaces)


Building the unsigned transaction body with Delegation Certificate
ledgerowner.deleg.cert certificates:  /tmp/ledgerowner.payment.txbody

{
    "type": "TxBodyAllegra",
    "description": "",
    "cborHex":
"82a500818258204b9e7c37958a18ffbdb39ce0d9ce70778cd7e89137ce39197736f191238a704f00018182583901cb1a8f014e7768ca49a1e6c7aa3bcee79ae1ad3dca2e49591d13e7bb0ab6b98c1bcd001f2a8ea298c899d217272f04e769c76d5562430ed11a00258e1d021a0002bf35031a014c8a45048183028200581c0ab6b98c1bcd001f2a8ea298c899d217272f04e769c76d5562430ed1581ca7ce13b0e41364cfc59bfe81d499ee412b6d2cb13cbef01155743e87f6"
}


Sign the unsigned transaction body with the ledgerowner.payment.skey &
ledgerowner.staking.skey:  /tmp/ledgerowner.payment.tx

Cardano App Version 2.1.0 found on your Ledger device!
Please approve the action on your Hardware-Wallet (abort with CTRL+C) ...
DONE

{
    "type": "Tx AllegraEra",
    "description": "",
    "cborHex":
"83a500818258204b9e7c37958a18ffbdb39ce0d9ce70778cd7e89137ce39197736f191238a704f00018182583901cb1a8f014e7768ca49a1e6c7aa3bcee79ae1ad3dca2e49591d13e7bb0ab6b98c1bcd001f2a8ea298c899d217272f04e769c76d5562430ed11a00258e1d021a0002bf35031a014c8a45048183028200581c0ab6b98c1bcd001f2a8ea298c899d217272f04e769c76d5562430ed1581ca7ce13b0e41364cfc59bfe81d499ee412b6d2cb13cbef01155743e87a10082825820eb4c5db859636d0aa51e2141f33d26e17aa25f72f809f0d1302888262cb9b34158401b165b5fdf466683cc4b5fab8b9059249eb1aa8a292ab46a3d2d3b4f4f1311c6a319effc816a679ffd83749085b206c48559c1b0e0e8884718f8b4724de19305825820bd5f19fad7d1befbd3b55ce3cc1fd8cb68f55668a58c49df1ba266da1db430b65840a62471b519736f803ac24a74f8a97034cd9bf0f5efc86d8b9ccd06bf3a09f8bc39d44eac02d5f8cea54159a8d0eedd563cc90bf195e77123e0f309c77d38d108f6"
}
Does this look good for you ? [y/N] y

Submitting the transaction via the node...DONE

**Comment by stackBlock** [comment]
here is the verification:

anthony@anthony-XPS-2720:~/cardanoSavvy/savvy$
03c_checkStakingAddrOnChain.sh ledgerowner

Version-Info: cli 1.25.1 / node 1.25.1 Scripts-Mode: online

Checking ChainStatus of Stake-Address-File ledgerowner.staking.addr:
stake1uy9tdwvvr0xsq8e2363f3jye6gtjwtcyua5uwm24vfpsa5gyldxwv

Staking Address is on the chain !

Account is delegated to a Pool with ID:
pool15l8p8v8yzdjvl3vml6qafx0wgy4k6t938jl0qy24wslgw7xlhc2

**Comment by gitmachtl** [comment]
hmm... ok, the ledger is the account with the 2.46ADA on it. than your old owner account is not delegating to the pool currently. so you have to run 06 for the old owner again to also delegate it to the pool.

**Comment by stackBlock** [comment]
Everything is going along well but I need to buy another hard wallet because you can only put one account on each nano s.
I was looking at the trezor but it is way more expensive but it looks like you can have more then one account on it, is that correct? Can I have 3 separate accounts on one trezor? It will make it a lot more cost effective if this is true but I can't find anything online to confirm this. Do you know if this is true?

Also, on a side note, are you writing scripts for token creation? I am going to start learning that today but I see that you already have your 01_sendLovelaces.sh and 01_sendAssets.sh ready for the update. 

Thanks again,
Anthony

**Comment by gitmachtl** [comment]
Yes you can switch the Trezor into the "passphrase" mode. In this mode you must provide an extra password to access another "wallet". And thats only limited to i think 100 accounts or so. You can activate the 2nd Pin for the Ledger too to have a 2nd Account on it. 

The scripts for Token creation are already finished, tested and available. But they are in the testnet folder, not in the mainnet folder to not confuse the people. So feel free to play around with tokens on the  Testnets. The README in the testnet folder already contains example on how to create/send/burn tokens :smiley:

**Comment by gitmachtl** [comment]
There is also another way to use more accounts on the ledger, this is for different userpaths. I think it can also go up to around 100 accounts. This is a feature not enable yet in my scripts, but would be easy to implement. Currently i think adalite is the only other wallet that supports these account at the moment. I could make you a version if you need it?

**Comment by gitmachtl** [comment]
I think i should release a version that can use multiple subaccounts on a ledger device for the payment(base) keys.

**Comment by stackBlock** [comment]
I don't much care which wallet I use my ledger with. I do like Daedalus but if using a different wallet will save me couple hundred dollars in HW purchases, I am all for it. Just let me know which wallet is the best to install and I will take care of it.
I am trying to learn / be involved with a much as I can with Cardano so If you need someone to test your your scripts or other things your working on, I would love to help. 
Thanks,
Anthony

**Comment by gitmachtl** [comment]
There are two types of multiple accounts on the hardware wallets:
- Passphrase-Style: This will present keys to the wallet software always via the normal 1852H/1815H/0H/0/0 path for payment and1852H/1815H/0H/2/0 for staking
- Account-Style: This works by using different Paths, for example using 1852H/1815H/0H/0/0 for the first normal account, 1852H/1815H/1H/0/0 for the next account, 1852H/1815H/2H/0/0 for the next account, and so on...

If you wanna use GUI wallets like Daedalus, Adalite, Yoroi, it depends on each wallet what type of "multiaccount" they support. The CLI can support all of them. Let me try some things out with the "Account-Style" model and a Nano...

**Comment by gitmachtl** [comment]
So, it looks like you can have up to 2^31 accounts on a single ledger device :smile:

This should be enough i think?

I have made a version for scripts 03a to support this, do you wanna try it?

**Comment by gitmachtl** [comment]
Please pick script 02 and/or 03a from the testnet folder if you wanna try out multiple accounts on the ledger/trezor via path-accounts. :smile:

**Comment by stackBlock** [comment]
I will check that out. What current GUI wallets support the account-style? I can understand why they ledger doesn't advertise these features, they would a lot less products... I will let you know how it goes..

**Comment by gitmachtl** [comment]
I think currently only Adalite.io supports this on MainNet. But you have to fill up the "accounts" from 0 (default) up. So using index 1 next and so on. Otherwise Adalite would not recognize it, because the wallet is looking at the next account index, and stops if there is nothing in it. 

Of course you can always interact with your hw wallets via the CLI.

**Comment by stackBlock** [comment]
I just want to make sure I am understanding how to do this:
In the original directions for using a hard wallet , we only need to run 03b_regStakingAddrCert.sh ledgerowner ledgerowner.payment in order to register the staking cert.
But, if you are using an additional address on ledger, you must first run 03a_genStakingPaymentAddr.sh to generate the address (because it is not the first address on ledger?) before you can run 03b_regStakingAddrCert.sh  (with the newly created address from 03a). Is that the correct reasoning or if I am incorrect, why do you need to run 03a before 03b when you use and additional leger address?

**Comment by stackBlock** [comment]
I just re-read it... looks like I got it mixed up... looks like 02 is for payment address and 03a is for a staking address..  scrap the question above... sorry about that...

**Comment by stackBlock** [comment]
I think perhaps I did something incorrectly. I ran: `02_genPaymentAddrOnly.sh ledger2 hw 1` 
It asked me to verify everything on my ledger - I did that.
then I sent a few ada to the new address (ledger2). 
I verified that it was received. 
Plugged into adalite and only my first account was showing, the second account was not showing.
perhaps I created an account in in the wrong slot and it did not show (as you said it would not if I didn't create accounts in succession) ?

**Comment by gitmachtl** [comment]
hi, please use 03a to generate addresses. i don't think adalite can handle enterprise (paymentonly) addresses on multiaccounts. :smile: 

but, you can contact me on telegram @atada_stakepool so we can do a follow up there.

**Comment by stackBlock** [comment]
I left a message on the telegram channel and then I think I got banned... IDK, I can't get back to the channel.. 
I tried again and it says: 597 members, 88 online
but I seem to be banned. I am not sure why... either way, thanks for all your help.

**Comment by gitmachtl** [comment]
This is strange, @atada_stakepool is my personal telegram account. Can you send me a PM?
