### ISSUE TITLE
Path ERROR - Config IS pointed correctly

### ISSUE THREAD

**Issue by Xevrac** [gitmachtl/scripts#21]
Hi all, 

Could be just me but I've triple checked. 

I have configured the scripts to point to my shelley genesis file but I am presented with this error when testing. 
`
xnode@xnode:~/.local/bin$ 00_common.sh 

Version-Info: cli 1.25.1 / node 1.25.1		Scripts-Mode: online

Path ERROR - Path to the shelley genesis file is wrong or the file is missing!

If you think all is right at your side, please check the GitHub repo if there
is a newer version/bugfix available, thx: https://github.com/gitmachtl/scripts
`

Here is my paths in the config please tell me if I'm doing this wrong. 

`
socket="/home/cnode/sockets/node.socket"

genesisfile="/home/cnode/config/mainnet-shelley-genesis.json"           #Shelley-Genesis path
genesisfile_byron="/home/cnode/config/mainnet-byron-genesis.json"       #Byron-Genesis path

cardanocli="cardano-cli"	#Path to your cardano-cli you wanna use
cardanonode="cardano-node"	#Path to your cardano-node you wanna use
`

Now if I follow that directory structure it takes me DIRECTLY to my shelley file. So I'm quite confused as to what may be wrong. Any suggestions would be awesome. 

Finally, my scripts are located in /home/.local/bin for convenience

**Comment by gitmachtl** [comment]
First, you don't have to run 00_common.sh, you may source it but in general, 00_common.sh is only called from the other scripts.

Do you have a common.inc somewhere? All entries in there overwrite your entries in the 00_common.sh.

**Comment by gitmachtl** [comment]
Can you please download the version from the testnet folder here and rerun it? This should now output the path the script is looking for.

https://github.com/gitmachtl/scripts/blob/master/cardano/testnet/00_common.sh

**Comment by Xevrac** [comment]
Hey will look into further soon enough. I was only running script directly
to test if it was working. I was setting up wallet and the error also
persisted per using your script.

I will try new file you've provided when I can. Will let you know how it
goes.

Thanks

**Comment by Xevrac** [comment]
Hi @gitmachtl, I updated the script and the issue persisted but now with your path output I worked out your problem. Your script automatically adjusts the path from defined path to a altered path including a "/cardano/" directory. This does not exist in my case. See below; 

My defined path in the common.sh = "/home/cnode/config/mainnet-shelley-genesis.json"
The path that it's being output when error = "/home**/cardano/**cnode/config/mainnet-shelley-genesis.json"

**Comment by Xevrac** [comment]
Attempting to run commands for eg. `02_genPaymentAddrOnly.sh myWallet cli
ls -al`

Presents me with the same error, what shall I do to fix this?

**Comment by gitmachtl** [comment]
This is strange because there is no hardcoded directory in any of those scripts. 

Do you have a **common.inc** file in your script directory, in your current directory or a **.common.inc** file in your $HOME directory?

**Comment by gitmachtl** [comment]
Any news about your issue?

**Comment by Xevrac** [comment]
> Any news about your issue?

Hi, I sent an email. It mustnt of gone through it appears. I'll screenshot and send here directly

**Comment by Xevrac** [comment]
Not that I can see no.. where else can I look for such a file. It may be clashing with your script perhaps? Here's all my directories. Unless I'm missing something. I really hope you can help me get to the bottom of this. Thank you

![malafjcjppbalppe](https://user-images.githubusercontent.com/19704346/108041640-eb4a8e00-7092-11eb-820a-96ca0b0534dd.png)
![phgmoaeghbcccbbh](https://user-images.githubusercontent.com/19704346/108041646-ec7bbb00-7092-11eb-92e1-837659c31428.png)
![oideigeknlcinfjk](https://user-images.githubusercontent.com/19704346/108041652-eede1500-7092-11eb-93fb-9891f9c52129.png)

**Comment by gitmachtl** [comment]
![image](https://user-images.githubusercontent.com/47434720/108044280-5ddf4d80-7042-11eb-901d-a6772d608f3e.png)

**Comment by Xevrac** [comment]
> ![image](https://user-images.githubusercontent.com/47434720/108044280-5ddf4d80-7042-11eb-901d-a6772d608f3e.png)

OH lol, I'll have a look into that file and adjust file path if referenced in there. Sorry to be all newbie at this. I am familiar with linux to an extent.

Would you mind educating me on the purpose of this file and its point in linking to other scripts?

**Comment by gitmachtl** [comment]
you can delete this file if you don't need it. the `common.inc` and `.common.inc` files are here for you to help you storing your personal settings. you can adjust them of course in the 00_common.sh, but if you update the scripts the 00_common.sh will be overwritten with a new version with more features. so to keep your personal settings you can have a `common.inc` file in a subdirectory somewhere together with your keys and addresses for example. the 00_common.sh reaches out on every call to include those files before execution. so if you wanna safe your cardano-cli/node path for example or your genesis path and be able to do easy script updates, you can put theses values into the common.inc and it will not be overwritten by a scripts-update.

**Comment by Xevrac** [comment]
Makes plenty of sense explained that way. I appreciate your time explaining
and helping me out, I'll change these settings tomorrow and let you know
how I go. But I assume youre very right and this should fix my problem :)
