### ISSUE TITLE
Error Formatting

### ISSUE THREAD

**Issue by MrMitch17** [gitmachtl/scripts#25]
https://github.com/gitmachtl/scripts/blob/f99e99e5b3aecb7429b1c3034c7cb9c99dce434b/cardano/mainnet/05a_genStakepoolCert.sh#L173

Says 64 chars, but its checking for 250.

**Comment by gitmachtl** [comment]
thx for that, yes it is a typo, the 64chars is incorrect. the check against 250 chars is correct. will be fixed in the next update.

**Comment by gitmachtl** [comment]
Actually i have to research again, there are currently a few different specifications floating around, let me check it.

**Comment by gitmachtl** [comment]
ok, so the max. number of chars for the description is actually 255. and the url of the stakepool homepage is not limited at all. this is covered by the total size of the metadata json of 512 bytes in total. the value will be corrected from 250 to 255 in the next update.
