### ISSUE TITLE
Trying to Mint Asset with Custom MetaData - Error Building Raw TX Data

### ISSUE THREAD

**Issue by MrMitch17** [gitmachtl/scripts#26]
I am trying to implement CIP 27 in one of my NFTs that I am trying to Mint using 11a. When passing it the metadata of "pct": 0.05  it looks like its converting it to a e value. rather than just 0.05

This is the error that I got.  I was trying to follow CIP 27 for 
Command failed: transaction build-raw  Error: Error reading metadata at: "metadata.json"
JSON schema error within the metadata item 777: {"abc123abc":{"0008":{"pct":5.0e-2
JSON numbers must be integers. Unexpected value: 5.0e-2

https://github.com/cardano-foundation/CIPs/pull/116

Passed Metadata

{
  "721": {
    "XXXX": {
      "0008": {
        "name": "XXX",
        "Description": "XX",
        "Collection": "X",
        "Generation": 1,
        "URL": "XXXX",
        "image": "XXXXX",
        "mediaType": "image/png",
        "files": [
          {
            "mediaType": "image/png",
            "src": "XXXXXX"
          }
        ]
      }
    }
  },
  "777":{
    "XXX":{
      "0008":{
        "pct": 0.05,
        "addr": "XXXXXX"
      }
    }
  }
}

**Comment by gitmachtl** [comment]
Hi, this is unrelated to the SPO scripts. But you can try to use as string. Looks like the CLI does not like a decimal numbers in JSONs. You can try to send it as string if the CIP is ok with that.

**Comment by MrMitch17** [comment]
Thanks so much for looking into this!  I was following this comment which made me believe it was expecting a a float vs a string.

https://github.com/cardano-foundation/CIPs/pull/116#issuecomment-913820668

I do see now what you are referencing in the CIP to use a string for 5% being "0.05"  I'll just use that for now! 

Thank you for your time!
