### ISSUE TITLE
cardano 1.32.1 support

### ISSUE THREAD

**Issue by thornenathan28** [gitmachtl/scripts#30]
Version 1.32.1 ERROR - Please use a cardano-cli version between 1.27.0 and 1.31.0 !
Other versions are not supported for compatibility issues, please check if newer scripts are available - thx.

If you think all is right at your side, please check the GitHub repo if there
is a newer version/bugfix available, thx: https://github.com/gitmachtl/scripts

**Comment by gitmachtl** [comment]
hi, please make sure you always update the 00_common.sh in your local instance! looks like you're working with a previous one.

-> https://github.com/gitmachtl/scripts/blob/master/cardano/mainnet/00_common.sh
