### ISSUE TITLE
Error: Extended public key export cancelled by user

### ISSUE THREAD

**Issue by parlange** [gitmachtl/scripts#31]
Hi,

Following the guide, I installed the bridge for Trezor T via deb file and cardano-hw-cli on my local node.

While trying to export its public keys with:

`cardano-hw-cli address key-gen
  --path 1852H/1815H/0H/2/0
  --verification-key-file hw-stake.vkey
  --hw-signing-file hw-stake.hwsfile`

I get the following error even with the Trezor T unlocked:

`Error: Extended public key export cancelled by user`

I have tried on multiple ubuntu 20.04 installations without success. How can I export both hw-stake.vkey and hw-stake.hwsfile?

Thank you

**Comment by gitmachtl** [comment]
Hi, what versions of the hw-cli and trezor model-t are you using?

**Comment by parlange** [comment]
Following Coincashew guide to secure pĺedge with HW

`wget https://github.com/vacuumlabs/cardano-hw-cli/releases/download/v1.2.0/cardano-hw-cli_1.2.0-1.deb
sudo dpkg --install ./cardano-hw-cli_1.2.0-1.deb`

[CoinCashew 18.14](https://www.coincashew.com/coins/overview-ada/guide-how-to-build-a-haskell-stakepool-node/18.-operational-and-maintenance-tips#18.14-secure-your-pool-pledge-with-a-2nd-pool-owner-using-a-hardware-wallet
)

Trezor T (bought 1 year ago on January)
Firmware: 2.4.3
Has PIN
Is unlocked while running commands
It is already staking to the pool, as the guide suggests.
Wallet works fine with Trezor Suite 21.2.2, just not by CLI.

I cannot execute this command to extract the keys:

`cardano-hw-cli address key-gen \
  --path 1852H/1815H/0H/2/0 \
  --verification-key-file **hw-stake.vkey** \
  --hw-signing-file **hw-stake.hwsfile**`

Thank you

**Comment by gitmachtl** [comment]
Please follow the guide on **this** repo, not on the Coincashew one 😄 

https://github.com/gitmachtl/scripts/tree/master/cardano/mainnet#readme

Here are the steps to prepare the system for Model-T and HW-CLI, the version you use for HW-CLI is way too old. Current HW-CLI Version is 1.9.1 !

Here is the link to the section about HW-Wallets:
https://github.com/gitmachtl/scripts/tree/master/cardano/mainnet#how-to-prepare-your-system-before-using-a-hardware-wallet

HW-CLI (deb-package) 1.9.1:
https://github.com/vacuumlabs/cardano-hw-cli/releases/download/v1.9.1/cardano-hw-cli_1.9.1-1.deb

**Comment by gitmachtl** [comment]
Is it working? Can we close the issue?

**Comment by parlange** [comment]
Hi @gitmachtl 

Yes, it is now working just fine. Using Cardano HW CLI v1.9.1 I was able to export public keys from the Trezor T (.vkey and .hwsfile).

Thank you very much
