### ISSUE TITLE
Error: Failed to decode neither the cli's serialisation format nor the ledger's CDDL serialisation format.

### ISSUE THREAD

**Issue by wcatz** [gitmachtl/scripts#33]
Working with ARM64. Hopefully you can give me some insight into this error. Is this a bech32 error originating from offline machine? I obviously cannot run any of the included binary's. I know I am in uncharted territory. The bech32 binary I built on an aarch64 Ubuntu using a newer libc6 than what is available on this Debian arm server. This is what I think is happening but wanted to see if you had any ideas from the error message before I start rebuilding anything. I do not recall needing bech32 for pool registration on testnet. 

Error is happening on mainnet execute

This is while reregistering onchain data. Error happens on mainnet online machine during execute with cli wallet/s. 

What is encoding/decoding serialisation format?

> Command failed: transaction txid  Error: Failed to decode neither the cli's serialisation format nor the ledger's CDDL serialisation format. TextEnvelope error: /dev/fd/63: TextEnvelope type error:  Expected one of: TxSignedByron, TxSignedShelley, Tx AllegraEra, Tx MaryEra, Tx AlonzoEra Actual: Witnessed Tx AlonzoEra
> TextEnvelopeCddl error: /dev/fd/63: Could not JSON decode TextEnvelopeCddl file at: /dev/fd/63 Error: Error in $: not enough input
> TxID will be:

Thank you Martin

**Comment by gitmachtl** [comment]
bech32, it depends, if native assets are involved into the transaction because they are on the payment address for example than its needed. otherwise the tx output would not be correct. but i actually have no idea about this error, all scripts changed to cddl format for the latest node 1.34.1 version. but it says "not enough input". so i would retry it with a working bech32 binary. otherwise its an arm issue with the tools.

**Comment by wcatz** [comment]
Poking around I see this.

https://github.com/input-output-hk/cardano-node/issues/3688

Difference being I am trying to execute an already signed(I think it's signed) tx. The transaction is just a reregistration.

>    {
>       "date": "Tue, 03 May 2022 06:57:02 -0400",
>       "action": "signed pool registration transaction for 'OTG', payment via 'smallwallet1'"
>     }

I will dig further and pull latest into testnet pool to test, thank you Martin.

**Comment by HofmannZ** [comment]
@gitmachtl - I'm seeing the same issue. Will do some testing on my end.

**Comment by HofmannZ** [comment]
Rolled back to node/cli version 1.33.1 and reset scripts to e895bff5490d62a157eda82b4fde61798f2e606f that works all fine.

It may be because of the new `--cddl-format` flag, and not sure how this is ARM related. Would have to test on a x86 machine but don't have a spare one around.

**Comment by gitmachtl** [comment]
Looks like an ARM issue yes. Can't do much about that. Please submit an issue report on the cardano-node repo:
https://github.com/input-output-hk/cardano-node/issues

**Comment by ArchiFleKs** [comment]
I actually have the same issue in testnet with v1.35.2 on x86. When I work online, I can easily run `05a` then `05c` with success to update my stake pool parameter, but when I try to work offline and moving the offline transfer from offline host to online host I have the same error:

```
Command failed: transaction txid  Error: Failed to decode neither the cli's serialisation format nor the ledger's CDDL serialisation format. TextEnvelope error: /dev/fd/63: TextEnvelope type error:  Expected one of: TxSignedByron, Tx
SignedShelley, Tx AllegraEra, Tx MaryEra, Tx AlonzoEra, Tx BabbageEra Actual: Witnessed Tx AlonzoEra                                                                                                                                     
TextEnvelopeCddl error: /dev/fd/63: Could not JSON decode TextEnvelopeCddl file at: /dev/fd/63 Error: Error in $: not enough input                                                                                                       
TxID will be:        
```

**Comment by ArchiFleKs** [comment]
Cardano version used on both offline and online:
```
cardano-cli 1.35.2 - linux-x86_64 - ghc-8.10
git rev 7612a245a6e2c51d0f1c3e0d65d7fe9363850043
```

**Comment by gitmachtl** [comment]
Have you updated to the new 01_workOffline.sh file in the mainnet folder? There is currently a bug in the CLI that does not allow piping for certain commands. 

https://github.com/gitmachtl/scripts/blob/master/cardano/mainnet/01_workOffline.sh

**Comment by ArchiFleKs** [comment]
Ok my bad @gitmachtl my repo was not up to date on online machine but was on offline one, thank you.

**Comment by gitmachtl** [comment]
No problem, is it working now?

**Comment by ArchiFleKs** [comment]
> No problem, is it working now?

Yes I managed to pass the TX on the online machine
