### ISSUE TITLE
ERROR (Code 1) ! when sending tokens

### ISSUE THREAD

**Issue by jterrier84** [gitmachtl/scripts#34]
Not possible to send tokens with the command 01_sendAssets.sh

Example command: sudo ./01_sendAssets.sh addr1 addr2 afc910d7a306d20c12903979d4935ae4307241d03245743548e76783.ASHIB ALL

I get as error message:
...
3 Asset-Type(s) / 3 different PolicyIDs found on the Address!

Assets to send (given input reference, * means selected via bulk sending):                Amount: Bech-Format:                                
(standard_in) 2: syntax error
(standard_in) 5: syntax error
./01_sendAssets.sh: line 511: [[: 1
-4999999999
1: syntax error in expression (error token is "1")
afc910d7a306d20c12903979d4935ae4307241d03245743548e76783.ASHIB                     5000000000
1
1                                             

Assets remaining after transaction - PolicyID:          Asset-Name:                       Amount: Bech-Format:                                  Ticker:  Meta-Name:
afc910d7a306d20c12903979d4935ae4307241d03245743548e76783.ASHIB                         5000000000                                               ASHIB    ADA Shiba Inu 
ba3afde69bb939ae4439c36d220e6b2686c6d3091bbc763ac0a1679c6269745f626f7420307830303035                1                                                        
f0ff48bbb7bbe9d59a40f1ce90e9e9d0ff5002ec48f232b49ca0fb9a.mini1pool                    -4999999999                                                        

option --tx-out: 
unexpected "\n"
expecting hexadecimal digit
expecting a 56 hex-encoded policy ID, but found only 1 hex digits

Usage: cardano-cli transaction build-raw 
            [ --byron-era
            | --shelley-era
            | --allegra-era
            | --mary-era
            | --alonzo-era
            ]
            [--script-valid | --script-invalid]
            (--tx-in TX-IN
              [--tx-in-script-file FILE
                [
                  ( --tx-in-datum-cbor-file CBOR FILE
                  | --tx-in-datum-file JSON FILE
                  | --tx-in-datum-value JSON VALUE
                  )
                  ( --tx-in-redeemer-cbor-file CBOR FILE
                  | --tx-in-redeemer-file JSON FILE
                  | --tx-in-redeemer-value JSON VALUE
                  )
                  --tx-in-execution-units (INT, INT)]])
            [--tx-in-collateral TX-IN]
            [--required-signer FILE | --required-signer-hash HASH]
            [--tx-out ADDRESS VALUE
              [ --tx-out-datum-hash HASH
              | --tx-out-datum-hash-cbor-file CBOR FILE
              | --tx-out-datum-hash-file JSON FILE
              | --tx-out-datum-hash-value JSON VALUE
              | --tx-out-datum-embed-cbor-file CBOR FILE
              | --tx-out-datum-embed-file JSON FILE
              | --tx-out-datum-embed-value JSON VALUE
              ]]
            [--mint VALUE
              (--mint-script-file FILE
                [
                  ( --mint-redeemer-cbor-file CBOR FILE
                  | --mint-redeemer-file JSON FILE
                  | --mint-redeemer-value JSON VALUE
                  )
                  --mint-execution-units (INT, INT)])]
            [--invalid-before SLOT]
            [--invalid-hereafter SLOT]
            [--fee LOVELACE]
            [--certificate-file CERTIFICATEFILE
              [--certificate-script-file FILE
                [
                  ( --certificate-redeemer-cbor-file CBOR FILE
                  | --certificate-redeemer-file JSON FILE
                  | --certificate-redeemer-value JSON VALUE
                  )
                  --certificate-execution-units (INT, INT)]]]
            [--withdrawal WITHDRAWAL
              [--withdrawal-script-file FILE
                [
                  ( --withdrawal-redeemer-cbor-file CBOR FILE
                  | --withdrawal-redeemer-file JSON FILE
                  | --withdrawal-redeemer-value JSON VALUE
                  )
                  --withdrawal-execution-units (INT, INT)]]]
            [--json-metadata-no-schema | --json-metadata-detailed-schema]
            [--auxiliary-script-file FILE]
            [--metadata-json-file FILE | --metadata-cbor-file FILE]
            [--genesis FILE | --protocol-params-file FILE]
            [--update-proposal-file FILE]
            [--cddl-format | --cli-format]
            --out-file FILE

  Build a transaction (low-level, inconvenient)

  Please note the order of some cmd options is crucial. If used incorrectly may produce undesired tx body. See nested [] notation above for details.

ERROR (Code 1) !

**Comment by gitmachtl** [comment]
hi, can you please provide more information about your system. what cardano-node/cli version are you using? are you using the latest version of the SPO scripts?

**Comment by gitmachtl** [comment]
i think i found your address its the one with also the adahandle right? i tried it here and it is working fine, can build the transaction with your example above.

**Comment by jterrier84** [comment]
Hi, my OS is Ubuntu and I'm using cli version 1.34.1. How were you able to build the tx? Yes my address is the one with ADA Handle $mini1pool. I'm desperately trying to move my NFT's with no success unfortunatley. Could you please provide any guidance? Thanks

**Comment by jterrier84** [comment]
How important is bech32 for 01_sendAssets.sh? Because I receive another error at the beginning. Here the entire log:

sudo ./01_queryAddress.sh mini1_main.payment

Version-Info: cli 1.34.1 / node 1.34.1		Scripts-Mode: online

Checking UTXOs of Address-File mini1_main.payment.addr: addr1qxgthckcrnkg0edew4hpzlnat300pg8j829srj639z320u9k84eg5mq93xp9faer7xsnd3f5c94l3c9l7q6nr06rnjgquhz7jz

Address-Type / Era: payment / shelley

3 UTXOs found on the Address!

Hash#Index: 0abed530237ea5d5b794ca855e4e6e269e16a4843856b779861979aee83ff019#0	ADA: 1.344798 (1344798 lovelaces)
./bech32: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./bech32)
./bech32: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./bech32)
./bech32: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./bech32)
                           Asset:   Amount: 5000000000 ASHIB
Hash#Index: 29958bd6a3c01498d2d6e794a1d3ab92b1b8ef66c30efdf76f0d6eccb94b683e#1	ADA: 1.586172 (1586172 lovelaces)
./bech32: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./bech32)
./bech32: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./bech32)
./bech32: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./bech32)
                           Asset:   Amount: 1 {6269745f626f7420307830303035}
./bech32: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./bech32)
./bech32: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./bech32)
./bech32: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./bech32)
                           Asset:   ADA Handle: $mini1pool mini1pool
Hash#Index: 5750e1aa0dd427131ad74d87b20abbaa19945fbd644897c4227b87e6237d0bef#0	ADA: 3.100000 (3100000 lovelaces)
-----------------------------------------------------------------------------------------------------
Total ADA on the Address: 6.030970 ADA / 6030970 lovelaces 

3 Asset-Type(s) / 3 different PolicyIDs found on the Address!

PolicyID:                                               Asset-Name:       Total-Amount: Bech-Format:                                  Ticker:  Meta-Name:
afc910d7a306d20c12903979d4935ae4307241d03245743548e76783.ASHIB               5000000000                                               ASHIB    ADA Shiba Inu 
ba3afde69bb939ae4439c36d220e6b2686c6d3091bbc763ac0a1679c6269745f626f7420307830303035                1                                                        
f0ff48bbb7bbe9d59a40f1ce90e9e9d0ff5002ec48f232b49ca0fb9a.mini1pool                    1                                                        

ubuntu@ubuntu:~/stakepoolscripts/bin$ sudo ./01_sendAssets.sh mini1_main.payment julien.nami ba3afde69bb939ae4439c36d220e6b2686c6d3091bbc763ac0a1679c6269745f626f7420307830303035 1

Version-Info: cli 1.34.1 / node 1.34.1		Scripts-Mode: online

./bech32: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./bech32)
./bech32: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./bech32)
./bech32: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./bech32)
Sending assets from Address mini1_main.payment.addr to Address julien.nami.addr:

Current Slot-Height: 64572394 (setting TTL[invalid_hereafter] to 64672394)

Source Address mini1_main.payment.addr: addr1qxgthckcrnkg0edew4hpzlnat300pg8j829srj639z320u9k84eg5mq93xp9faer7xsnd3f5c94l3c9l7q6nr06rnjgquhz7jz 
Destination Address julien.nami.addr: addr1qygv5fqsfjhfgkx7fhkkegxksx56dsu262vhaxr4mvuukt8uqh7nhjs3pcl98xr2zhmtqk6qkmr4gszxjrs3lnpedqdqyr3jzc 

3 UTXOs found on the Source Address!

Hash#Index: 0abed530237ea5d5b794ca855e4e6e269e16a4843856b779861979aee83ff019#0	ADA: 1.344798 (1344798 lovelaces)
./bech32: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./bech32)
./bech32: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./bech32)
./bech32: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./bech32)
                           Asset:   Amount: 5000000000 ASHIB
Hash#Index: 29958bd6a3c01498d2d6e794a1d3ab92b1b8ef66c30efdf76f0d6eccb94b683e#1	ADA: 1.586172 (1586172 lovelaces)
./bech32: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./bech32)
./bech32: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./bech32)
./bech32: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./bech32)
                           Asset:   Amount: 1 {6269745f626f7420307830303035}
./bech32: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./bech32)
./bech32: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./bech32)
./bech32: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./bech32)
                           Asset:   ADA Handle: $mini1pool mini1pool
Hash#Index: 5750e1aa0dd427131ad74d87b20abbaa19945fbd644897c4227b87e6237d0bef#0	ADA: 3.100000 (3100000 lovelaces)
-----------------------------------------------------------------------------------------------------
Total ADA on the Address:  6.030970 ADA / 6030970 lovelaces 

3 Asset-Type(s) / 3 different PolicyIDs found on the Address!

Assets to send (given input reference, * means selected via bulk sending):                Amount: Bech-Format:                                
(standard_in) 2: syntax error
(standard_in) 3: syntax error
ba3afde69bb939ae4439c36d220e6b2686c6d3091bbc763ac0a1679c6269745f626f742030783030                1                                             

The assetAmount on this address or on the selected UTXOs is not enough. A maximum of 5000000000
1
1 is available!

**Comment by gitmachtl** [comment]
yes, looks like your bech32 binary is not working like it should. aarch64 architecture is a problem. the bech32 binary in the scripts is for amd64 x86 architecture. it will not work with aarch. but you can try to compile an aarch version yourself of the bech32 binary. https://github.com/input-output-hk/bech32

**Comment by jterrier84** [comment]
Problem solved! In fact I had to do the following steps:
1) Replace the bech32 binary with an arm64 build
2) Upgrade Ubuntu to version 22.04 (becuase bech32 needs GLIBC version > 2.32)

**Comment by gitmachtl** [comment]
perfect! 😄
