### ISSUE TITLE
Last step of stakepool creation 

### ISSUE THREAD

**Issue by skilain** [gitmachtl/scripts#35]
Is there a way to fix this issue?

ERROR - Online(auto) and Offline(alonzo) Era mismatch!
![image](https://user-images.githubusercontent.com/85642726/184477513-33cb4fbf-d93f-4b8e-b83b-66b4378c11d3.png)

**Comment by gitmachtl** [comment]
what version are you using? do you use the latest version in the mainnet folder?

**Comment by gitmachtl** [comment]
please reopen if you still have problems, thx.
