### ISSUE TITLE
Filename of resolved handle address displayed instead of handle in 01_sendlovelaces.sh

### ISSUE THREAD

**Issue by deshawes** [gitmachtl/scripts#36]
./scripts/01_sendLovelaces.sh wallet/smallwallet4 '$arcter' ALL
     
         Version-Info: cli 1.35.3 / node 1.35.3          Scripts-Mode: online            Mainnet
						
	  Found $adahandle '$arcter' on Address: addr1qys8....... 7zl
	  Sending lovelaces from Address wallet/smallwallet4.addr to Address /tmp/adahandle-resolve.addr:

also at

         Lovelaces to send to /tmp/adahandle-resolve.addr:  9.828779 ADA / 9828779 lovelaces

**Comment by gitmachtl** [comment]
yes the script creates a temporary address file in the tmp folder. normally you have the address files ready on the hdd. the intention behind showing the file was to have a confirmation again that the right address was choosen. the file -> address is shown resolved at the top.

**Comment by deshawes** [comment]
Yes, it would be consistent  to reshow the e input to the command , showing the  handle $arcter ,  instead of the  temporary working file.  The name of the temp file means little to the user. 
Just a cosmetic change, I am easy either way.

**Comment by gitmachtl** [comment]
Changed it. Currently in Testnet-Folder, will be moved to Mainnet-Folder too later on.
