### ISSUE TITLE
Git clone installation instructions

### ISSUE THREAD

**Issue by abashai** [gitmachtl/scripts#37]
When I run the git fetch origin && git reset --hard orgin/master command, I get an error, "fatal not a git respository (or any of the parent directories): .git

I followed the steps in order.

**Comment by gitmachtl** [comment]
Hi, thanks for pointing it out. Looks like there were some git changes. I have updated the instructions, can you retry it?

Its working fine in my test (leaving out the PATH setting...):
![image](https://user-images.githubusercontent.com/47434720/193399644-a304208e-8d77-4862-a648-8ab6cfa0b8a2.png)

**Comment by gitmachtl** [comment]
Any updates? Otherwise i will close this issue. Thx.
