### ISSUE TITLE
Error Reported in 00_Common.sh

### ISSUE THREAD

**Issue by samcgill29** [gitmachtl/scripts#4]
I used script 03a_genStakingPaymentAddr.sh

output gives error encountered in 00_common.sh

Here is error output:

date: invalid date ‘null’
/opt/cardano/cnode/scripts/00_common.sh: line 89: (1591368418-) / 21600 : syntax error: operand expected (error token is ") / 21600 ")
Mimimum Registration Transfer Fee:  171221 lovelaces
Key Deposit Fee:  400000 lovelaces

**Comment by gitmachtl** [comment]
do you use the latest genesis file and cardano-node/cli 1.13.0? they changed the "startTime" key in the genesis now to "systemStart"

**Comment by samcgill29** [comment]
Yes, latest genesis and new cli release.

**Comment by samcgill29** [comment]
I found the problem.  I update the script manually and didn't change startTime to systemStart.  Thanks!  Issue closed.
