### ISSUE TITLE
Create the StakePool with multiple owners HW-Wallet-Owner-Keys (Ledger)

### ISSUE THREAD

**Issue by HuguesD** [gitmachtl/scripts#42]
I'm missing the steps example in the documentation for creating a multiple owners hw (ledger) stake pool.

What steps have to be added or changed in this example for multi-owners ? 
https://github.com/gitmachtl/scripts/tree/master/cardano/mainnet#create-the-stakepool-with-hw-wallet-owner-keys-ledger-and-encrypted-cli-keys

PS : I tried to contact you via your discord handle but it does not exist apparently.

thanks

**Comment by gitmachtl** [comment]
Hi, its the same as with normal MultiOwners, see the example here:
https://github.com/gitmachtl/scripts/tree/master/cardano/mainnet#register-a-multiowner-stakepool

**Comment by HuguesD** [comment]
Ok. I will combine in one documentation all of the info+examples that are required in the creation of a muli owner stake pool using HW ledger for the owners accounts and encrypted CLI for the stake pool keys. I will transmit it to you if you want to add it to the github as a step by step procedure. I will execute it also to check it, of course.

Thanks a lot for your kind and prompt help
