### ISSUE TITLE
Some Scripts Have Empty TTL

### ISSUE THREAD

**Issue by Crypto2099** [gitmachtl/scripts#44]
https://github.com/gitmachtl/scripts/blob/bd6358d15548191c6fe7a606d4c43757abdf74ec/cardano/mainnet/11a_mintAsset.sh#LL176C1-L176C1

if I bring in a script to be used here and the script uses the "all" syntax but only contains a signing key, this line in the scripts does not correctly get set to "unlimited" and is instead set to an empty string. So we should check for whether or not this is an empty string or not as well.

Example script that causes error:
```json
{
  "scripts": [
    {
      "keyHash": "64...6c",
      "type": "sig"
    }
  ],
  "type": "all"
}
```

**Comment by Crypto2099** [comment]
Example of the result when attempting to mint using the policy script above:

```shell
Policy valid before Slot-Height:

Current Slot-Height: 92947560 (setting TTL[invalid_hereafter] to )

Error - Your given Policy has expired, you cannot use it anymore!
```

**Comment by gitmachtl** [comment]
Thx @Crypto2099 , fixed with https://github.com/gitmachtl/scripts/commit/294c1666cd7a1d2fd7246e20e6d943c34656deea
