### ISSUE TITLE
How to rotate KES Key in offline mode ?

### ISSUE THREAD

**Issue by ids4ucmoi** [gitmachtl/scripts#47]
Hi,
To rotate the KES key and Opcert, there are the 04c and 04d scritps.
However I have an offline machine which contains my BP node keys.
Is it possible to rotate the KES key and Opcert on the offline machine ? If so I do not understand how the scripts can get the "online" required info to do that ?
I could run the 01 script on the online machine but with which arguments for a KEY rotation objective ? (there is no payument to do)

Can you help ?

Thanks

**Comment by ids4ucmoi** [comment]
Ok. I tried running both scripts on the airgap machine. I first set manually the date and time to the current date and time.
However the 04d script creates an opcert with a current KES period of 499 (which is wrong, the current KES period is 742).
I'm lost here on what to do to correct this ?

**Comment by ids4ucmoi** [comment]
Ignore my previous post. Date and time was still incorrect on the airgap, therefore the KES period was wrong.
So I 'm gonna bring the two files opver to the BP node and check that it works with 04e now

**Comment by ids4ucmoi** [comment]
I confirm it is ok now. Last noob question : now that I have extracted (01_workoofline.sh extract...) both KES and opcert files onto the BP node, can I simply rename them to match the previous two files and do a systemctl restart cardano.service ?

**Comment by gitmachtl** [comment]
Yes sure, the 01_workOffline.sh method is just a simple method to bring over some files. Would also be possible to simply copy them file by file. After its extracted you can rename it how you like of course.

**Comment by ids4ucmoi** [comment]
Ok, thanks very much for your help ! Ticket solved and closed.

**Comment by ids4ucmoi** [comment]
Hello,
 
Still another potential issue.
 
After running the 04 e script : I get the following :
***@***.***:~/production$ 04e_checkNodeOpCert.sh myPool.node.opcert  current
 
Version-Info: cli 8.1.1 / node 8.1.1            Scripts-Mode: online            Mainnet
 
Checking OpCertFile myPool.node.opcert for the correct OpCertCounter and KES-Interval:
 
Current EPOCH: 420
 
 
KES-Interval Check: OK, within range
 
    Current KES Period: 742
 File KES start Period: 742
File KES expiry Period: 804
   File KES expires in: 92 days 09:33:12
 
 
OpCertCounter Check - CURRENTLY used: FALSE, OnChain Counter NOT equal to File Counter
 
Latest OnChain Counter: 0
       File Counter is: 1
 
 
So is this an issue or should I start over and set the counter back to 0 instead of 1 ?
 
Thanks
 
Hugues Dorchy
ids4u Srl
M : +32 (0)495 55 79 53
E : ***@***.***

**Comment by gitmachtl** [comment]
Hi, no this is not an issue. Because the node cane only check against a correct new online version once another block was made with that version. Your last used opcert counter on chain was 0, so the new one should be 1. You've generated that with 1. If you run the script 04e with the flag "next" instead of "current" you will get a greenlight. 

At the moment, the new opcert counter/cert only exists on your blockproducer harddisc. The chain does not know about it until you've me at least one new block.

**Comment by gitmachtl** [comment]
You have made a block in the past right? Can you tell me your Ticker?

If you have made a block in the past with opCertCounter=0, you update it now to opCertCounter=1 together with the KES-Key renewal. So the next block that your BP will make, will be with opCertCounter=1.

**Comment by ids4ucmoi** [comment]
Ok I understand. Ticker is IDS4U
The current opcert counter in adapools is 0 on my last produced block.
So I understand my next produced block wil use this new opcert certificate with counter=1 and Adapools will update this info then. 
 
Hugues Dorchy
ids4u Srl
M : +32 (0)495 55 79 53
E : ***@***.***
