### ISSUE TITLE
Ledger-Cardano-App 6.0.3 is unavailable

### ISSUE THREAD

**Issue by ihorzenich** [gitmachtl/scripts#49]
Your script requires Cardano-App v6.0.3 or above to be installed on the Ledger for Catalyst-Voting-Registration. But unfortunately, I can't find version 6 using `Experimental Features -> My Ledger provider -> Enable it and set it to 4`.

Please tell me how to install Cardano-App v6, thanks!
![Ledger-Cardano-App 6 0 3](https://github.com/gitmachtl/scripts/assets/1684521/b07d53a0-2715-4cc3-94de-25b36a23bf89)

**Comment by gitmachtl** [comment]
Hi,

i guess you are refering to the 09a_catalystVote.sh script. 

Ledger has removed the Cardano-App version 6.0.3 from the Provider 4, you can use version 5.0.1. For that i created the script 09a_catalystVote**F10**.sh

Best regards,
 Martin

**Comment by ihorzenich** [comment]
Yes, we are talking about the 09a_catalystVote.sh script.
Unfortunately, the 09a_catalystVoteF10.sh script also gives the following error:
![Ledger-Cardano-App 6 0 3 F10](https://github.com/gitmachtl/scripts/assets/1684521/63dbfd3a-1c55-45b2-b31e-4e181151f60a)

**Comment by gitmachtl** [comment]
Oh, you wanna create a hw voting key. Thats not possible right now. Just simply generate a normal cli voting key please like:
`09a_catalystVoteF10.sh new cli myvote`

You don't need a hw based voting key to register your hw wallet with it.

**Comment by gitmachtl** [comment]
Did it work?

**Comment by ihorzenich** [comment]
I have a cardano-pool where the owner is 2 wallets:
1) cli, where a little ada
2) hw Ledger, where almost all of ada is

As far as I understand, in order to Catalyst vote with my pool pledge, I have to register from hw wallet, right?

**Comment by gitmachtl** [comment]
> I have a cardano-pool where the owner is 2 wallets:
> 
> 1. cli, where a little ada
> 2. hw Ledger, where almost all of ada is
> 
> As far as I understand, in order to Catalyst vote with my pool pledge, I have to register from hw wallet, right?

You need to sign the registration with your hw wallet yes, but not generating also the voting key on the hw wallet.

So all you have to do is basically:

1. `09a_catalystVoteF10.sh new cli myvote` to generate a voting key on the cli
2. `09a_catalystVoteF10.sh genmeta myvote hw-wallet-account rewardpaymentaddr` to generate the registration cbor metadata and sign it with your hw wallet
3. `01_sendLovelaces.sh mywallet mywallet min xxx.vote-registrationcbor` to submit the cbor on chain
4. `09a_catalystVoteF10.sh qrcode myvote 1234` to generate the qr code for the voting app.
5. after a while (~hours) you can check the registration via `09a_catalystVoteF10.sh query myvote`
