### ISSUE TITLE
Script compatibility with latest major upgrade Cardano node 8.7.2 and future 9.0 ?

### ISSUE THREAD

**Issue by ids4ucmoi** [gitmachtl/scripts#50]
Hello Martin,

I'm willing to upgrade my stake pool cardano node from current 8.1.1 to the latest major upgrade 8.7.2. I'm using your scripts to manage our stake pool (tahnk you for that by the way, what would we do without you ?). My question is if there is any impact of this cardano major upgrade to take into account with your scripts or not ?

Thank you
Hugues

**Comment by gitmachtl** [comment]
@ids4ucmoi hi, yes there are a lot of changes for the new cli and also for upcoming conway era. i have already uploaded the latest scripts for node 8.7.2 into the "testnet" folder. you can use them right away if you want. i will update the mainnet folder and README over the coming weekend.

**Comment by ids4ucmoi** [comment]
Thank you
