### ISSUE TITLE
Update require to hyperlink in README.md

### ISSUE THREAD

**Issue by deshawes** [gitmachtl/scripts#6]
The README example "Update stakepool parameters on the blockchain"
contains an old hyperlink, Unlock ,  to ff-testnet script 

1. **Unlock** the existing mypool.pool.json file and edit it. .....

**Comment by deshawes** [comment]
Also in "Change" in script info 
05a_genStakepoolCert.sh: 
.
.
want to **change** some parameters, simply change them in the json file and rerun the script again

**Comment by gitmachtl** [comment]
internal links changed, thx.
