### ISSUE TITLE
Security documentation.

### ISSUE THREAD

**Issue by matiwinnetou** [gitmachtl/scripts#7]
Security Documentation:

Maybe it is totally obvious to the owner but a more beginner user may find it hard to know which keys are to be protected and ideally not stored on the server and if they are stored on the server then protected with chmod 600 (root only):

The whole shebang of keys and files generated:
```
-r--------  1 mati wheel  1517 Jun 25 23:31 mypool.kes-000.skey
-r--------  1 mati wheel   142 Jun 25 23:31 mypool.kes-000.vkey
-r--------  1 mati wheel     4 Jun 25 23:31 mypool.kes.counter
-r--------  1 mati wheel   141 Jun 26 00:02 mypool.kes-expire.json
-r--------  1 mati wheel   150 Jun 26 00:02 mypool.metadata.json
-r--------  1 mati wheel   339 Jun 26 00:02 mypool.node-000.opcert
-r--------  1 mati wheel   103 Jun 26 00:02 mypool.node.counter
-r--------  1 mati wheel   151 Jun 25 23:31 mypool.node.skey
-r--------  1 mati wheel   161 Jun 25 23:31 mypool.node.vkey
-r--------  1 mati wheel   620 Jun 26 00:02 mypool.pool.cert
-r--------  1 mati wheel   907 Jun 26 00:03 mypool.pool.json
-r--------  1 mati wheel   195 Jun 25 23:31 mypool.vrf.skey
-r--------  1 mati wheel   133 Jun 25 23:31 mypool.vrf.vkey
-r--------  1 mati wheel    59 Jun 25 23:12 mywallet.addr
-r--------  1 mati wheel   130 Jun 25 23:12 mywallet.skey
-r--------  1 mati wheel   142 Jun 25 23:12 mywallet.vkey
-r--------  1 mati wheel   203 Jun 26 00:02 owner.deleg.cert
-r--------  1 mati wheel   115 Jun 25 23:30 owner.payment.addr
-r--------  1 mati wheel   130 Jun 25 23:30 owner.payment.skey
-r--------  1 mati wheel   142 Jun 25 23:30 owner.payment.vkey
-r--------  1 mati wheel    63 Jun 25 23:30 owner.staking.addr
-r--------  1 mati wheel   141 Jun 25 23:30 owner.staking.cert
-r--------  1 mati wheel   130 Jun 25 23:30 owner.staking.skey
-r--------  1 mati wheel   142 Jun 25 23:30 owner.staking.vkey
-rw-r--r--  1 mati wheel   486 Jun 26 00:03 protocol-parameters.json
```

In other words, which keys are absolutely necessary for stake pool operation until KES expires.

The idea here is that if an attacker gets access to the machine (including root), will she be able to steal rewards, will she be able to steal the pledge... how to prevent this.

**Comment by gitmachtl** [comment]
well, the question is where to start with that. i don't wanna make a whole server security discussion, there are dozens of things to keep in mind. but first, you should not do the pool setup on your server, thats why i included a sample 0x_upload... script. 
files are currently locked with 400 to make sure they are not overwritten or deleted by the user by accident, this is not security related at that point. so on the coreNode you only need the vrf.skey, latest opcert and latest kes.skey. 
if you wanna include something like that, can you edit the readme.md and add a "security" section and make a pull-request?

**Comment by matiwinnetou** [comment]
Yeah I can prepare a PR. Thanks for your hard work!

**Comment by gitmachtl** [comment]
thx. we can also do a link collection about server security if we find some useful links i guess? :-)

**Comment by matiwinnetou** [comment]
Server security I think is something else, there is plenty of resources regarding this, here situation is a bit special, a user maybe simply lost with all keys generated and there is no material on the internet how to protect it. Here we are talking about pledge and staking rewards, which maybe considerable amount when person doesn't take right measures. 

Things like:
1. never running app from root
2. firewall configuration
3. making sure all latest versions are updated
4. exposing ssh on port different than 22

and millions others - really do not belong in this guide as they are more general knowledge IMHO.
