### ISSUE TITLE
Checking ledger state doesn't work on 1.14.1

### ISSUE THREAD

**Issue by matiwinnetou** [gitmachtl/scripts#9]
1. I cannot check my staking address
2. I cannot check if my pool is registered

e.g. 

05d_checkPoolOnChain.sh
I went and looked a bit:
```
[mati@cardano ~]$ cardano-cli shelley query ledger-state --testnet-magic 42 | grep "poolPubKey"
[mati@cardano ~]$
```
this simply always produces empty results, which means there is no poolPubKey anymore

I would assume similar problem is with checking if staking address is registered:
03c_checkStakingAddrOnChain.sh
```
[mati@cardano ~]$ cardano-cli shelley query ledger-state --testnet-magic 42 | jq ._delegationState._dstate._stkCreds

parse error: Invalid numeric literal at line 1, column 7
```

**Comment by gitmachtl** [comment]
Have you read the readme notes? 

3rd line is saying:
TESTED FOR CARDANO-NODE TAG: 1.14.0 & 1.14.1, ledgerstate is currently broken so 03c/05d will not work !

This is a cardano-node issue.

**Comment by matiwinnetou** [comment]
No I have not seen this, thank you.
